<?php

/**
 * @file
 * Contains the hook implementations.
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function flagship_programs_theme($existing, $type, $theme, $path) {
  return [
    'flagship_program__table' => [
      'render_element' => 'children',
      'template' => 'flagship-program--table',
      'path' => $path . '/templates',
      'variables' => [
        'data' => NULL,
      ],
    ],
    'flagship_program_list' => [
      'render_element' => 'children',
      'template' => 'flagship-program--list',
      'path' => $path . '/templates',
      'variables' => [
        'data' => NULL,
      ],
    ],
    'webform_paragraph_view' => [
      'render_element' => 'children',
      'template' => 'webform-paragraph',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_suggestions_HOOK().
 */
function flagship_programs_theme_suggestions_flagship_program__table_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'flagship_program__table';
}

/**
 * Implements hook_suggestions_HOOK().
 */
function flagship_programs_theme_suggestions_flagship_program__list_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'flagship_program__list';
}

/**
 * Implements hook_entity_view_alter().
 */
function flagship_programs_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  $node = $entity->getEntityTypeId();
  if ($node && $entity->bundle() == 'movie') {
    echo 'hello';
    $build['#attached'] = [
      'library' => ['simplesmart/simple-js']
    ];
  }
}
