<?php

/**
 * @file
 * 
 * Contains the hook impletemnation
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Messenger\Messenger;
use Drupal\Core\Render\Element\Url;
use Drupal\Core\Url as CoreUrl;

 /**
  * Implementing the hook_permission()
  */
function helloworld_permission() {
  return array(
    'administer hello module' => array(
      'title' => t('Administer my module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}

/**
 * Implementing the hook_help module
 */
function helloworld_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.helloworld':
      return '<p>' . '<h3>' . t('Its a custom Page') . '</h3>' . t('Where your name and the email id will be printed  provided you are logged in, also it has a feature of printing the content based on route parameter,') . '<br> <i>' . t('This Page is being brought by implementing the ') . '<strong><a href="https://api.drupal.org/api/drupal/core%21modules%21help%21help.api.php/function/hook_help/10">hook_help()</a></strong> </i>' . '</p>';
  }
}

/**
 * Implementing the hook_hello_greet()
 */
function helloworld_hello_greet(int $count, string $bundle_name, array &$build) {
  // \Drupal::messenger()->addMessage(t('You have viewed this page @count times in current session',['@count' => $count]));
  $build['hello_world'] = [
    '#type' => 'markup',
    '#markup' => t('This Entity is of <strong> @bundle_type </strong> type and it has been visited <strong> @count </strong> times', ['@bundle_type' => $bundle_name, '@count' => $count]),
    '#cache' => array(
      'max-age' => 0
    ),
  ];
}

/**
 * Implementing the hook_entity_view()
 */
function helloworld_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  //Initiating a session variable to store the viewing count of different nodes
  $session = \Drupal::request()->getSession();

  //Getting the name of the session and the type of data it needs to store
  $current_count = $session->get('node_view_count', array());

  //Checking if an entity with given id has been visited or not
  $current_count[$entity->id()] = !isset($current_count[$entity->id()]) ? 1 : ++$current_count[$entity->id()];
  $session->set('node_view_count', $current_count);
  $module_handler = \Drupal::moduleHandler();

  //Invoking all the hooks with given name and passing the required parameters
  //to them
  $module_handler->invokeAll('hello_greet',array($current_count[$entity->id()], $entity->bundle(), &$build));
}

/**
 * Implementing the hook_theme()
 */
function helloworld_theme($existing, $type, $theme, $path) {
  $information = [
    'helloworld_theme_hook' => [
      'render_element' => 'children',
      'template' => 'helloworld-theme-hook',
      'path' => $path . '/templates',
      'variables' => [
        'var1' => 'Vishal Prasad',
        'var2' => 10,
        'var3' => ['vishal', 'ajay', 'birat'],
      ],
    ],
  ];

  return $information;
}

/**
 * Implements hook_form_alter().
 */
function helloworld_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'user_login_form') {
     $form['#submit'][] = 'myredirect_submit_handler';
  }
}

/**
* Custom submit handler for login form.
*/
function myredirect_submit_handler($form, FormStateInterface $form_state) {

  $redirect_service = \Drupal::service('helloworld.route_service');
  $redirect_service->redirectAfterSubmit('helloworld.custom_welcome_page', $form, $form_state);
}
