<?php

/**
 * @file
 *   Contains the Hook Implementation for the module
 */

/**
 * Implementing the hook_theme()
 */
function custom_field_theme($existing, $type, $theme, $path) {
  $information = [
    'dynamic-background-color' => [
      'render_element' => 'children',
      'template' => 'custom_field-theme',
      'path' => $path . '/templates',
      'variables' => [
        'color' => '#ff1234',
      ],
    ],
  ];
  return $information;
}